Project=SPRINT NOTES
Environment=QA
Execution=Jenkins
Framework=Pytest
Browser=Chrome
OS=Windows 10
Python=3.14.3
API.Tests=Enabled
UI.Tests=Enabled
Integration.Tests=Enabled
Parallel.Execution=3 Workers
Tester=Akshita